server:
  port: 8080
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: user-service
  main:
    allow-circular-references: true
  profiles:
    active:
      - prod
      - oauth

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
