server:
  port: 8080

spring:
  application:
    name: user-service
  main:
    allow-circular-references: true
  profiles:
    active:
      - prod
      - oauth

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secretKey: ${secret}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh